language: node_js
node_js:
- '0.10'

before_script:
- npm install grunt-cli -g
- python -m SimpleHTTPServer &

# travis automatically runs `npm test` for the main script

after_script:
- killall python
